### ISSUE TITLE
Dreambooth: RuntimeError: expected scalar type Half but found Float Traceback (most recent call last):

### ISSUE THREAD

**Issue by senornz** [ShivamShrirao/diffusers#118]
### Describe the bug

Everything was working for previous runs, but now getting this error each time I try and run the training.

I see this issue raised and closed by someone running locally:

[https://github.com/ShivamShrirao/diffusers/issues/117](https://github.com/ShivamShrirao/diffusers/issues/117)

But I can't see where to upgrade diffusers package on Colab as it looks like is being downloaded fresh each time in the "install requirements with:

`%pip install -qq git+https://github.com/ShivamShrirao/diffusers`

### System Info

Colab Notebook

**Comment by ShivamShrirao** [comment]
Should be fixed now. 3a21df300312708dbc1304633d6a96280043aa31

**Comment by ProGamerGov** [comment]
@ShivamShrirao Its still broken if you are using full precision training: https://github.com/ShivamShrirao/diffusers/issues/123
