### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by mustafakucuk0** [ShivamShrirao/diffusers#39]
### Describe the bug

The code throws this error:

RuntimeError: expected scalar type Half but found Float

I tried different environments, closing and reopening mixed_precision in the config but it still throws this error.

Could you help me please?

### Logs

```shell
Time to load utils op: 0.0018088817596435547 seconds
Steps:   0%|                                                                                                                                                             | 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 646, in <module>
    main()
  File "train_dreambooth.py", line 591, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1666, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py", line 299, in forward
    encoder_hidden_states=encoder_hidden_states,
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 559, in forward
    create_custom_forward(attn), hidden_states, encoder_hidden_states
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 553, in custom_forward
    return module(*inputs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 169, in forward
    hidden_states = block(hidden_states, context=context)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 218, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 297, in forward
    return self.to_out(hidden_states)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
```

### System Info

- `diffusers` version: 0.6.0.dev0
- Platform: Linux-5.15.0-50-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.13
- PyTorch version (GPU?): 1.12.1 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by ShivamShrirao** [comment]
Hey, It should be fixed now.

**Comment by mustafakucuk0** [comment]
It still throws the same error. I rechecked everything to ensure the pipeline. Could you tell me what have you changed exactly? 

Thanks!

**Comment by mustafakucuk0** [comment]
![image](https://user-images.githubusercontent.com/46380931/196709655-cb373ebd-d6f0-482d-ba15-d5db7b07c72e.png)

**Comment by ShivamShrirao** [comment]
Did you download the latest version from this repo now ?

**Comment by mustafakucuk0** [comment]
Yes. I deleted my whole folder and extracted the repo into the new folder.

**Comment by mustafakucuk0** [comment]
Here is my full output:

```
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2022-10-19 16:51:51,903] [WARNING] [runner.py:178:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-10-19 16:51:51,928] [INFO] [runner.py:504:main] cmd = /home/lm/miniconda3/envs/dreambooth/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --no_local_rank train_dreambooth.py --pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4 --instance_data_dir=/home/lm/Desktop/photos/sevgi_preprocessed --class_data_dir=/home/lm/Desktop/Latent_Memories/Algorithms/Phase_1/dd/dreambooth/classes/sevgie --output_dir=/home/lm/Desktop/Latent_Memories/Algorithms/Phase_1/dd/dreambooth/weights/sevgie --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt=sks sevgie --class_prompt=sevgie --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --gradient_checkpointing --learning_rate=5e-6 --lr_scheduler=constant --lr_warmup_steps=0 --num_class_images=50 --max_train_steps=800 --mixed_precision=fp16
[2022-10-19 16:51:52,758] [INFO] [launch.py:136:main] WORLD INFO DICT: {'localhost': [0]}
[2022-10-19 16:51:52,758] [INFO] [launch.py:143:main] nnodes=1, num_local_procs=1, node_rank=0
[2022-10-19 16:51:52,758] [INFO] [launch.py:155:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2022-10-19 16:51:52,758] [INFO] [launch.py:156:main] dist_world_size=1
[2022-10-19 16:51:52,758] [INFO] [launch.py:158:main] Setting CUDA_VISIBLE_DEVICES=0
[2022-10-19 16:51:54,680] [INFO] [comm.py:635:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Caching latents: 100%|██████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:06<00:00,  7.40it/s]
[2022-10-19 16:52:14,015] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.7.3, git-hash=unknown, git-branch=unknown
[2022-10-19 16:52:14,410] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2022-10-19 16:52:14,411] [INFO] [logging.py:68:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2022-10-19 16:52:14,411] [INFO] [logging.py:68:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2022-10-19 16:52:14,451] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Basic Optimizer = {basic_optimizer.__class__.__name__}
[2022-10-19 16:52:14,451] [INFO] [utils.py:53:is_zero_supported_optimizer] Checking ZeRO support for optimizer=AdamW type=<class 'torch.optim.adamw.AdamW'>
[2022-10-19 16:52:14,451] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
[2022-10-19 16:52:14,451] [INFO] [stage_1_and_2.py:134:__init__] Reduce bucket size 500000000
[2022-10-19 16:52:14,451] [INFO] [stage_1_and_2.py:135:__init__] Allgather bucket size 500000000
[2022-10-19 16:52:14,451] [INFO] [stage_1_and_2.py:136:__init__] CPU Offload: True
[2022-10-19 16:52:14,451] [INFO] [stage_1_and_2.py:137:__init__] Round robin gradient partitioning: False
Using /home/lm/.cache/torch_extensions/py37_cu113 as PyTorch extensions root...
Emitting ninja build file /home/lm/.cache/torch_extensions/py37_cu113/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.2529423236846924 seconds
Rank: 0 partition count [1] and sizes[(859520964, False)] 
[2022-10-19 16:52:16,482] [INFO] [utils.py:827:see_memory_usage] Before initializing optimizer states
[2022-10-19 16:52:16,483] [INFO] [utils.py:832:see_memory_usage] MA 1.68 GB         Max_MA 1.68 GB         CA 3.29 GB         Max_CA 3 GB 
[2022-10-19 16:52:16,483] [INFO] [utils.py:837:see_memory_usage] CPU Virtual Memory:  used = 10.83 GB, percent = 34.6%
[2022-10-19 16:52:21,294] [INFO] [utils.py:827:see_memory_usage] After initializing optimizer states
[2022-10-19 16:52:21,294] [INFO] [utils.py:832:see_memory_usage] MA 1.68 GB         Max_MA 1.68 GB         CA 3.29 GB         Max_CA 3 GB 
[2022-10-19 16:52:21,295] [INFO] [utils.py:837:see_memory_usage] CPU Virtual Memory:  used = 20.82 GB, percent = 66.6%
[2022-10-19 16:52:21,295] [INFO] [stage_1_and_2.py:516:__init__] optimizer state initialized
[2022-10-19 16:52:21,324] [INFO] [utils.py:827:see_memory_usage] After initializing ZeRO optimizer
[2022-10-19 16:52:21,324] [INFO] [utils.py:832:see_memory_usage] MA 1.68 GB         Max_MA 1.68 GB         CA 3.29 GB         Max_CA 3 GB 
[2022-10-19 16:52:21,324] [INFO] [utils.py:837:see_memory_usage] CPU Virtual Memory:  used = 20.82 GB, percent = 66.6%
[2022-10-19 16:52:21,324] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Final Optimizer = AdamW
[2022-10-19 16:52:21,324] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed using client LR scheduler
[2022-10-19 16:52:21,325] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2022-10-19 16:52:21,325] [INFO] [logging.py:68:log_dist] [Rank 0] step=0, skipped=0, lr=[5e-06], mom=[(0.9, 0.999)]
[2022-10-19 16:52:21,325] [INFO] [config.py:987:print] DeepSpeedEngine configuration:
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   activation_checkpointing_config  {
    "partition_activations": false, 
    "contiguous_memory_optimization": false, 
    "cpu_checkpointing": false, 
    "number_checkpoints": null, 
    "synchronize_checkpoint_boundary": false, 
    "profile": false
}
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True}
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   amp_enabled .................. False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   amp_params ................... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   autotuning_config ............ {
    "enabled": false, 
    "start_step": null, 
    "end_step": null, 
    "metric_path": null, 
    "arg_mappings": null, 
    "metric": "throughput", 
    "model_info": null, 
    "results_dir": null, 
    "exps_dir": null, 
    "overwrite": true, 
    "fast": true, 
    "start_profile_step": 3, 
    "end_profile_step": 5, 
    "tuner_type": "gridsearch", 
    "tuner_early_stopping": 5, 
    "tuner_num_trials": 50, 
    "model_info_path": null, 
    "mp_size": 1, 
    "max_train_batch_size": null, 
    "min_train_batch_size": 1, 
    "max_train_micro_batch_size_per_gpu": 1.024000e+03, 
    "min_train_micro_batch_size_per_gpu": 1, 
    "num_tuning_micro_batch_sizes": 3
}
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   bfloat16_enabled ............. False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   checkpoint_tag_validation_enabled  True
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   checkpoint_tag_validation_fail  False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   comms_config ................. <deepspeed.comm.config.DeepSpeedCommsConfig object at 0x7fcca7964bd0>
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   communication_data_type ...... None
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   compression_config ........... {'weight_quantization': {'shared_parameters': {'enabled': False, 'quantizer_kernel': False, 'schedule_offset': 0, 'quantize_groups': 1, 'quantize_verbose': False, 'quantization_type': 'symmetric', 'quantize_weight_in_forward': False, 'rounding': 'nearest', 'fp16_mixed_quantize': False, 'quantize_change_ratio': 0.001}, 'different_groups': {}}, 'activation_quantization': {'shared_parameters': {'enabled': False, 'quantization_type': 'symmetric', 'range_calibration': 'dynamic', 'schedule_offset': 1000}, 'different_groups': {}}, 'sparse_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'row_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'head_pruning': {'shared_parameters': {'enabled': False, 'method': 'topk', 'schedule_offset': 1000}, 'different_groups': {}}, 'channel_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'layer_reduction': {'enabled': False}}
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   curriculum_enabled ........... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   curriculum_params ............ False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   dataloader_drop_last ......... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   disable_allgather ............ False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   dump_state ................... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   dynamic_loss_scale_args ...... None
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_enabled ........... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_gas_boundary_resolution  1
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_layer_num ......... 0
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_max_iter .......... 100
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_stability ......... 1e-06
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_tol ............... 0.01
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   eigenvalue_verbose ........... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   elasticity_enabled ........... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   flops_profiler_config ........ {
    "enabled": false, 
    "profile_step": 1, 
    "module_depth": -1, 
    "top_modules": 1, 
    "detailed": true, 
    "output_file": null
}
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   fp16_auto_cast ............... True
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   fp16_enabled ................. True
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   fp16_master_weights_and_gradients  False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   global_rank .................. 0
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   gradient_accumulation_steps .. 1
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   gradient_clipping ............ 0.0
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   gradient_predivide_factor .... 1.0
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   initial_dynamic_scale ........ 4294967296
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   load_universal_checkpoint .... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   loss_scale ................... 0
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   memory_breakdown ............. False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   monitor_config ............... <deepspeed.monitor.config.DeepSpeedMonitorConfig object at 0x7fcca7964750>
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   nebula_config ................ {
    "enabled": false, 
    "persistent_storage_path": null, 
    "persistent_time_interval": 100, 
    "num_of_version_in_retention": 2, 
    "enable_nebula_load": true, 
    "load_path": null
}
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   optimizer_legacy_fusion ...... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   optimizer_name ............... None
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   optimizer_params ............. None
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0}
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   pld_enabled .................. False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   pld_params ................... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   prescale_gradients ........... False
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   scheduler_name ............... None
[2022-10-19 16:52:21,326] [INFO] [config.py:991:print]   scheduler_params ............. None
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   sparse_attention ............. None
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   sparse_gradients_enabled ..... False
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   steps_per_print .............. inf
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   train_batch_size ............. 1
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   train_micro_batch_size_per_gpu  1
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   wall_clock_breakdown ......... False
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   world_size ................... 1
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   zero_allow_untested_optimizer  True
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   zero_config .................. stage=2 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=500000000 allgather_partitions=True allgather_bucket_size=500000000 overlap_comm=False load_from_fp32_weights=True elastic_checkpoint=False offload_param=DeepSpeedZeroOffloadParamConfig(device='cpu', nvme_path=None, buffer_count=5, buffer_size=100000000, max_in_cpu=1000000000, pin_memory=False) offload_optimizer=DeepSpeedZeroOffloadOptimizerConfig(device='cpu', nvme_path=None, buffer_count=4, pin_memory=False, pipeline=False, pipeline_read=False, pipeline_write=False, fast_init=False) sub_group_size=1000000000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=50000000 param_persistence_threshold=100000 model_persistence_threshold=9223372036854775807 max_live_parameters=1000000000 max_reuse_distance=1000000000 gather_16bit_weights_on_model_save=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters=True legacy_stage1=False round_robin_gradients=False
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   zero_enabled ................. True
[2022-10-19 16:52:21,327] [INFO] [config.py:991:print]   zero_optimization_stage ...... 2
[2022-10-19 16:52:21,327] [INFO] [config.py:982:print_user_config]   json = {
    "train_batch_size": 1, 
    "train_micro_batch_size_per_gpu": 1, 
    "gradient_accumulation_steps": 1, 
    "zero_optimization": {
        "stage": 2, 
        "offload_optimizer": {
            "device": "cpu"
        }, 
        "offload_param": {
            "device": "cpu"
        }, 
        "stage3_gather_16bit_weights_on_model_save": false
    }, 
    "steps_per_print": inf, 
    "fp16": {
        "enabled": true, 
        "auto_cast": true
    }, 
    "zero_allow_untested_optimizer": true
}
Using /home/lm/.cache/torch_extensions/py37_cu113 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0012319087982177734 seconds
Steps:   0%|                                                                                                        | 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 688, in <module>
    main()
  File "train_dreambooth.py", line 627, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1666, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py", line 299, in forward
    encoder_hidden_states=encoder_hidden_states,
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 559, in forward
    create_custom_forward(attn), hidden_states, encoder_hidden_states
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 553, in custom_forward
    return module(*inputs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 169, in forward
    hidden_states = block(hidden_states, context=context)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 218, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 297, in forward
    return self.to_out(hidden_states)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
Steps:   0%|                                                                                                        | 0/800 [00:00<?, ?it/s]
[2022-10-19 16:52:23,804] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 8852
[2022-10-19 16:52:23,804] [ERROR] [launch.py:292:sigkill_handler] ['/home/lm/miniconda3/envs/dreambooth/bin/python', '-u', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=/home/lm/Desktop/photos/sevgi_preprocessed', '--class_data_dir=/home/lm/Desktop/Latent_Memories/Algorithms/Phase_1/dd/dreambooth/classes/sevgie', '--output_dir=/home/lm/Desktop/Latent_Memories/Algorithms/Phase_1/dd/dreambooth/weights/sevgie', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=sks sevgie', '--class_prompt=sevgie', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--max_train_steps=800', '--mixed_precision=fp16'] exits with return code = 1
Traceback (most recent call last):
  File "/home/lm/miniconda3/envs/dreambooth/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/accelerate/commands/launch.py", line 827, in launch_command
    deepspeed_launcher(args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/accelerate/commands/launch.py", line 540, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--no_local_rank', '--num_gpus', '1', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=/home/lm/Desktop/photos/sevgi_preprocessed', '--class_data_dir=/home/lm/Desktop/Latent_Memories/Algorithms/Phase_1/dd/dreambooth/classes/sevgie', '--output_dir=/home/lm/Desktop/Latent_Memories/Algorithms/Phase_1/dd/dreambooth/weights/sevgie', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=sks sevgie', '--class_prompt=sevgie', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--max_train_steps=800', '--mixed_precision=fp16']' returned non-zero exit status 1.
```

**Comment by mustafakucuk0** [comment]
Hello again!

I tried to reinstall diffusers package with the conda ( I installed with pip before). It works now. I do not know what was the exact solution but reinstalling with conda solved the problem

**Comment by ShivamShrirao** [comment]
Install with `pip install git+https://github.com/ShivamShrirao/diffusers.git`

**Comment by mustafakucuk0** [comment]
Hi again!

I reinstalled whole environment and tried but it still throws the same error.

**Comment by mustafakucuk0** [comment]
It works now by installing diffusers with conda. I do not know what is going on exactly.

![image](https://user-images.githubusercontent.com/46380931/196739613-62c00d2d-f779-43bf-baa3-cf1e2c807b3e.png)

**Comment by mustafakucuk0** [comment]
It works now by installing diffusers with conda. I do not know what is going on exactly.

![image](https://user-images.githubusercontent.com/46380931/196739826-5f1b5b93-0694-4fbc-b5b1-11552380a577.png)

**Comment by mustafakucuk0** [comment]
Hello Shivam. Thank you for your responses. But the most recent code still throws this error. 

`"RuntimeError: expected scalar type Half but found Float"`

I fixed this error by installing diffusers package via the conda channel. But after I install the library this way, the code only worked once and threw "CUDA out of memory" error while generating class images. The only fix for this error was to set up the python environment and install "diffusers" package with conda again.

Is there anything I can do to fix this error?
