### ISSUE TITLE
UnboundLocalError: local variable 'text_encoder' referenced before assignment

### ISSUE THREAD

**Issue by maxscheel-sr** [ShivamShrirao/diffusers#42]
### Describe the bug

Normal run thru colab
https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb

without gdrive and with`--gradient_checkpointing`

https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#L665

### Logs

```shell
Steps: 100% 1000/1000 [18:37<00:00,  1.11s/it, loss=0.193, lr=5e-6]Traceback (most recent call last):
  File "train_dreambooth.py", line 677, in <module>
    main()
  File "train_dreambooth.py", line 665, in main
    text_encoder=accelerator.unwrap_model(text_encoder),
UnboundLocalError: local variable 'text_encoder' referenced before assignment
Steps: 100% 1000/1000 [18:37<00:00,  1.12s/it, loss=0.193, lr=5e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

### System Info

https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb

T4, Colab free

**Comment by misbahsy** [comment]
The same error also happens with gdrive selected.

**Comment by InB4DevOps** [comment]
This also happens when running locally. 
A temporary workaround is to comment out line 665 in train_dreambooth.py (add `# ` in front of the line)

**Comment by InB4DevOps** [comment]
This also happens when running locally. 
A temporary workaround is to comment out (or delete) line 665 in train_dreambooth.py.

**Comment by lekhrajsaini0** [comment]
@InB4DevOps  wouldnt that affect the model somehow?

**Comment by pratham-saraf** [comment]
@InB4DevOps  wouldnt that brak the code ?

**Comment by InB4DevOps** [comment]
> @InB4DevOps wouldn't that brake the code somehow?

no, this only omits the keyword argument text_encoder. I tried the workaround and it works (locally).
For the notebook you'd have to make a fork and change the file in your repo.

**Comment by pratham-saraf** [comment]
@InB4DevOps  i rather changed the file in runtime and it worked as well

**Comment by ShivamShrirao** [comment]
Hey, I have updated the code with training for text_encoder, it should be fixed now and results are vastly better.

**Comment by mustafakucuk0** [comment]
Hello Shivam!

The code still throws this error. I am trying to train the model locally without fine-tuning the model. Just the 8 GB version of the code. But it still gives me this error. Could you look at the code again?
