### ISSUE TITLE
I am having trouble running train_dreambooth.py

### ISSUE THREAD

**Issue by Flun** [ShivamShrirao/diffusers#89]
I am having trouble calling it through my_training.sh. Please help.

My system: 5600x / 32gb / RTX3090 24gb
win11/wsl2 ubuntu/cuda 11.7 pytorch 1.12.0 cu116

code in my_training.sh

export MODEL_NAME="animefull-latest"
export INSTANCE_DIR="training"
export OUTPUT_DIR="model"
 
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="test style" \
  --mixed_precision="fp16" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=2500

Below is the error message.

./my_training.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `6` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/home/kona/github/diffusers/examples/dreambooth/train_dreambooth.py", line 765, in <module>
    main()
  File "/home/kona/github/diffusers/examples/dreambooth/train_dreambooth.py", line 489, in main
    import bitsandbytes as bnb
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py", line 125, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py", line 90, in determine_cuda_runtime_lib_path
    CUDASetup.get_instance.add_log_entry(f'{candidate_env_vars["CONDA_PREFIX"]} did not contain '
AttributeError: 'function' object has no attribute 'add_log_entry'
Traceback (most recent call last):
  File "/home/kona/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/kona/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=animefull-latest', '--instance_data_dir=training', '--output_dir=model', '--pretrained_vae_name_or_path=animefull-latest.vae', '--instance_prompt=test style', '--mixed_precision=fp16', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=2500']' returned non-zero exit status 1.

![image](https://user-images.githubusercontent.com/23303172/198284996-040f32a8-199a-4953-a4b7-0df662210839.png)

Please. It took me over 3 days to solve this problem, but there was no progress, so I decided to write a post.

**Comment by Flun** [comment]
I also watched and followed the guide in the link.

https://pastebin.com/uE1WcSxD

**Comment by Flun** [comment]
Thanks for the reply.
I just manually updated to 0.35.2 version via pip install git+https://github.com/TimDettmers/bitsandbytes.git command, but it still doesn't work.
Instead, the --use_8bit_adam function was removed and started, but it was successful.
There still seems to be a problem with bitsandbytes.


> This is caused by a wrong function call in the bitsandbytes library and is resolved in bitsandbytes version 0.35.2. Updating it should fix the problem.

**Comment by msamilg** [comment]
> Thanks for the reply. I just manually updated to 0.35.2 version via pip install git+https://github.com/TimDettmers/bitsandbytes.git command, but it still doesn't work. Instead, the --use_8bit_adam function was removed and started, but it was successful. There still seems to be a problem with bitsandbytes.
> 
> > This is caused by a wrong function call in the bitsandbytes library and is resolved in bitsandbytes version 0.35.2. Updating it should fix the problem.

Maybe you're getting a different error this time or the library hasn't been updated correctly. This particular error was caused by "CUDASetup.get_instance" not being called in line 90 in the file "bitsandbytes/cuda_setup/paths.py", and has been resolved in version 0.35.2.

**Comment by EddieGithub26** [comment]
I updated to bitsandbytes 0.35.2, but now I'm getting another error:
AttributeError: 'NoneType' object has no attribute 'cuDeviceGetCount'

**Comment by EddieGithub26** [comment]
So I fixed it by doing pip install --upgrade bitsandbytes, then, export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

**Comment by Flun** [comment]
> So I fixed it by doing pip install --upgrade bitsandbytes, then, export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

I did the same but it still doesn't work. (bitsandbytes 0.35.3)
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

The error code that occurs has been uploaded to the bitsandbytes git issue board. I hope this gets resolved.

**Comment by zakinp** [comment]
> The model succeeded in converting the 7gb animefull-latest.ckpt file into a 3.97gb folder through convert_original_stable_diffusion_to_diffusers.py.
> 
> It's too hard to run locally.

how to successfully convert the animefull-latest.ckpt file ? i use this script to convert the ckpt but a error occur: Unexpected key(s) in state_dict: ***many keys***
